---
version: 2.1

executors:
  golang:
    docker:
      - image: cimg/go:1.15

jobs:
  build:
    executor: golang
    steps:
      - checkout
      - run: "make binaries"
  test-success:
    executor: golang
    steps:
      - checkout
      - run: "make test-impl cmd-parser-text=echo"
  test-fail:
    executor: golang
    steps:
      - checkout
      - run: "! make test-impl cmd-parser-text=false"
